### ISSUE TITLE
how to get around global lock

### ISSUE THREAD

**Issue by jonathanstrong** [lukemetz/rustpy#15]
hey - I have a situation where I need to run some Python code from Rust but I will have many Python processes running simultaneously. I am advanced at Python but a beginner in Rust, so I thought I would reach out regarding how to get around the global lock in this library. Would I need to edit the code so that a new state generates a new Python process and has its own lock? Why did you pick a global lock in the first place (so I understand the hurdles to what I am planning)?

**Comment by lukemetz** [comment]
Hey,
Processes in python each have there own global lock. There are only issues when dealing with threads. If I remember correctly I used a single global lock / used the GIL because I wanted a single python process not many. Both threads and processes in python have there advantages and tradeoffs. Threads are less overhead and have low to zero cost communication but can't run python concurrently due to the GIL. Processes are high overhead make communication harder and harder to generally debug and work with but let one run concurrent code.
Hope that helps.
